import Head from 'next/head';
import Image from "next/image";
import {useState} from "react";
import Layout from "../components/Layout";
import Input from "../components/Input";
import Select from "../components/Select";
import Datepicker from "../components/Datepicker";

import Banner from "../assets/frontpage-illustration.svg";
import SelectInput from "../components/SelectInput";
import TextArea from "../components/TextArea";

const doctors = [
  { name: "A" },
  { name: "B" },
  { name: "C" },
  { name: "D" },
  { name: "E" },
  { name: "F" },
  { name: "G" },
];

export default function Home(props) {
  const [image, setImage] = useState(null);

  const [form, setForm] = useState({
    doctor: null
  });

  const handleChangeForm = (e) => {
    setForm({
      [e.target.name]: e.target.value
    });
  }

  const upload = async (e) => {
    e.preventDefault();

    const formData = new FormData();
    for (let i = 0; i < image.length; i++) {
      formData.append("image", image[i]);
    }

    await fetch("http://localhost:8000/api/upload", {
      method: "POST",
      body: formData
    });
  }

  const countries = [
    { name: "Indonesia" },
    { name: "Australia" },
    { name: "Singapore" },
  ];

  const slots = [
      "12:00 - 13:00",
      "12:00 - 13:00",
      "12:00 - 13:00",
      "12:00 - 13:00",
  ];

  return (
      <Layout>
        <Head>
          <title>Enkindle - Doctor Appointment</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="flex justify-between items-center">
          <div className="w-1/2 pl-20 pr-10">
            <h1 className="text-5xl font-bold leading-normal">Find Your Doctor and Make Appointment</h1>
            <p className="mt-2 text-sm">Make appointment with your doctor in our clinic. Set the date you choose and get your diagnose.</p>
            <button className="py-3 px-8 bg-primary rounded-2xl text-white text-sm mt-5">
              Make Appointment Now
            </button>
          </div>
          <Image src={Banner} height={700}/>
        </div>

        <div className="w-3/4 mx-auto mt-10">
          <h1 className="mb-14 text-5xl text-center">Make Appointment Now</h1>
          <div className="w-full grid grid-cols-2 gap-4">
            <div>
              <Select
                  label="Select Doctor"
                  name="doctor"
                  options={doctors}
                  value={form.doctor}
                  selected={form.doctor?.name}
                onChange={handleChangeForm}/>
            </div>
            <div>
              <Datepicker
                label="Datepicker"/>
            </div>
            <div>
              <Input
                  label="Doctor"/>
            </div>
            <div>
              <SelectInput
                label="Phone Number"
                options={countries}/>
            </div>
          </div>
          <div className="mt-4">
            <TextArea
                label="Description"
                rows={5}/>
          </div>

          <div className="mt-4">
            <p className="mb-0.5 text-sm">Slot Available</p>
            <div className="w-full grid grid-cols-8 gap-4">
              {slots.map((e, i) => (
                  <button key={i} className="h-11 border-2 border-gray-300 rounded-xl text-sm">{e}</button>
              ))}
            </div>
          </div>

          <button className="py-2.5 px-6 float-right bg-primary rounded-xl text-white text-sm mt-6">
            Make Appointment
          </button>
        </div>
      </Layout>
  )
}

export async function getServerSideProps(ctx) {
  // get the current environment
  let dev = process.env.NODE_ENV !== 'production';
  let { DEV_URL, PROD_URL } = process.env;

  // request posts from api
  let response = await fetch(`${dev ? DEV_URL : PROD_URL}/api/user`);
  // extract the data
  let data = await response.json();

  return {
    props: {
      users: data,
    },
  };
}